version: '3'
services:
    mongo-db:
        container_name: mongo-db
        image: mongo:5.0.28-focal # 5.0.28-focal https://hub.docker.com/layers/library/mongo/5.0.28-focal/images/sha256-fa87a93bb303eb07da4cfea8551c0a391eac485cd303c6cd39c67973d88f49da?context=explore
        restart: unless-stopped
        ports:
            - '27017:27017'
        expose:
            - '27017'
#    volumes:
#      - ./volumes/mongo:/data/db