server:
    servlet:
        context-path: /spring-boot-testing
    port: 9090
spring:
    application:
        name: Mockito testing
    data:
        mongodb:
            uri: mongodb://localhost:27017/product-service